### ISSUE TITLE
error

### ISSUE THREAD

**Issue by GGnoWP** [TrixiS/base-ts-bot#4]
![image](https://user-images.githubusercontent.com/83351891/213405408-faabed4e-269c-4a2b-abaa-92b64dc64619.png)

**Comment by TrixiS** [comment]
Erlpack is used for some speedups of discord.js. You can remove it from package.json or install git to resolve this error

**Comment by GGnoWP** [comment]
![image](https://user-images.githubusercontent.com/83351891/213409963-ac07e9e3-0eb4-4126-bb8d-fa68713da376.png)

**Comment by GGnoWP** [comment]
[2023-01-19T09_48_46_015Z-debug-0.log](https://github.com/TrixiS/base-ts-bot/files/10455556/2023-01-19T09_48_46_015Z-debug-0.log)
